repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: golang
        entry: ./golint.sh
        types: [ go ]
        files: ^zadanie_04/.*\.go$
        pass_filenames: false
