services:
  backend:
    build:
      context: ../zadanie_04
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CGO_ENABLED: 1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
